files:
  include: '**/*.s+(a|c)ss'

options:
  formatter: stylish
  merge-default-rules: false
rules:
  attribute-quotes: 1
  bem-depth:
    - 1
    - max-depth: 1
  border-zero:
    - 1
    - convention: 0
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 0
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  declarations-before-nesting: 1
  empty-args: 0
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: false
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 1
  force-pseudo-nesting: 0
  function-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 0
    - convention: hyphenatedbem
  indentation:
    - 0
    - size: 2
  leading-zero:
    - 0
    - include: false
  max-line-length:
    - 1
    - length: 120
  mixin-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations:
    - 0
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-keywords: 1
  no-color-literals: 0
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 1
  no-ids: 1
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 1
  no-transition-all: 0
  no-url-protocols: 0
  one-declaration-per-line: 1
  placeholder-in-extend: 1
  placeholder-name-format:
    - 0
    - convention: hyphenatedbem
  property-sort-order: 0
  property-units:
    - 1
    - global:
        - rem
        - '%'
        - s
        - vh
        - em
      per-property:
        html:
          - px
  quotes:
    - 1
    - style: single
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma: 1
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-for-property: 1
  variable-name-format:
    - 0
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 1
